---
- name: enable snap socket
  command: systemctl enable --now snapd.socket
  become: yes

- name: enable snap classic
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: yes

- name: install core snap
  community.general.snap:
    name: core
  #    classic: yes
  become: yes
#  environment:
#    PATH: "/var/lib/snapd/"
#  vars:
#    extra_path: /var/lib/snapd/snap

- name: install certbot
  community.general.snap:
    name: certbot
    classic: yes
  become: yes
  vars:
    extra_path: /var/lib/snapd/snap

- name: prepare certbot binary
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  become: yes
