---
# 1. install vault
# 2. configure vault
#   - /etc/vault.d/vault.hcl
#   - storage
#     just file storage for the time being
#   - network
#     open port 8200 and 80 (if certbot-SSL)
#     add local ip and domain to /etc/hosts
#   - TLS/certificates?
#     install snapd
#     install certbot through snapd
#     generate certs with "sudo certbot certonly --standalone"
#     chmod -R "u=rwX,g=rX" /etc/letsencrypt/{live,archive}
#   - start/enable vault service, export VAULT_ADDR
#   - chronyd replaced NTP - Audit to make sure it's appropriate
# 3. init
#   - manage seal tokens
# 4. unseal
# 5. AWS cli authentication - IAM
# 6. cli DB authentication

- name: update system packages
  dnf:
    name: "*"
    state: latest
  become: yes

# hacky solution, due to what appears to be a bug with enablerepo module
- name: Add HashiCorp yum repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  become: yes
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

# hacky solution, due to what appears to be a bug with enablerepo module
- name: Add EPEL yum repo
  command: dnf -y install epel-release
  become: yes
#  args:
#    creates:

- name: dnf-upgrade
  command: dnf -y upgrade
  become: yes

- name: install needed packages from repo's
  yum:
    enablerepo:
      - "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
      - "epel-release"
    name:
      - epel-release
      - vault
      - firewalld
    state: latest
  become: yes

- name: deploy vault.hcl template
  template:
    src: ./templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    force: yes
  become: yes

- import_tasks: ./network.yml

- name: copy TLS cert
  copy:
    src: ../files/fullchain.pem
    dest: /opt/vault/tls/fullchain.pem
    owner: root
    group: vault
    mode: "u=rw,g=r,o-rwx"
  become: yes

- name: copy TLS key
  copy:
    src: ../files/privkey.pem
    dest: /opt/vault/tls/privkey.pem
    owner: root
    group: vault
    mode: "u=rw,g=r,o-rwx"
  become: yes

- name: start/enable vault service
  systemd:
    name: vault
    state: started
    enabled: yes
  become: yes
